### PR TITLE
Release 0.0.3

### PR DESCRIPTION
**Pull request by akrherz**
refs #2

### CODE REVIEW

**Comment by guusdk** [comment]
@deleolajide are you aware that for the release of a plugin to show up on the website / in Openfire, a tag needs to be set on the first commit of this PR?

**Comment by deleolajide** [comment]
Thanks. Yes, I just became aware of this when trying to do that with Pade 1.4.1 a few weeks ago and failed to push to GitHub releases. Everything else worked. Not sure when the tag should be created. Is it with 0.0.3 or with 0.0.4-snapshot commit.

**Comment by guusdk** [comment]
Generally speaking, it is never desirable to tag code that is some kind of -SNAPSHOT. The reasoning for this is that Maven will be somewhat opportunistic when working with SNAPSHOTs. This means that every build could result in binaries that could be slightly different. That is obviously not good for a release, as that should be as predictable as possible.

To be able to create a build that is safely reproducible, we should strive to have _exactly one_ commit that defines the version number (in the POM file) to be a non-snapshot release. That then would be the commit from which all builds should be generated. That way, there will never be any ambiguity as to what state of the code (and the corresponding dependencies) are ment to make up the release.

With that logic, that commit (the singular one that defines a version without a -SNAPSHOT postfix) should also be the commit that should be tagged (as that tag will then represent the state-of-the-code on which the releases are build).

**Comment by deleolajide** [comment]
Thanks for the detailed explanation. What do we need to do to force a GitHub release 0.0.3 for this plugin? I assume it is too late to apply a tag for 0.0.3

See GitHub Actions screenshot below

image

**Comment by guusdk** [comment]
You are perfectly on track to follow what we normally do, in the same order as how we ordinarily do things too:

1. Make sure that the main branch contains all code changes that should be in the release
2. Create a PR that contains two separate commits: one that sets the version to a release (non-SNAPSHOT), followed immediately by one that set the version to a SNAPSHOT of the next version. (this will ensure that there is only one commit in which there is a non-SNAPSHOT version)
3. Merge (_without squashing_ as we want both commits to exist) to the main branch.
4. Set a git tag on the commit that had the version as a non-SNAPSHOT. This is done easiest by using the Github UI to create a release (which under water sets a git tag).

The fact that Github Actions already executed a build of the future SNAPSHOT does not matter at all. When you set the tag, Github Actions will run again.

**Comment by deleolajide** [comment]
Easy peasy, when you are shown how 👍 

image

**Comment by akrherz** [comment]
This is the screenshot of interest from [our website](https://igniterealtime.org/projects/openfire/plugins.jsp)

ss

**Pull request merged**
